INSERT INTO contatto VALUES ();
INSERT INTO contatto VALUES ();
INSERT INTO contatto VALUES ();
INSERT INTO contatto VALUES ();
INSERT INTO contatto VALUES ();
INSERT INTO contatto VALUES ();
INSERT INTO contatto VALUES ();
INSERT INTO contatto VALUES ();
INSERT INTO contatto VALUES ();
INSERT INTO contatto VALUES ();
INSERT INTO contatto VALUES ();
INSERT INTO contatto VALUES ();
INSERT INTO contatto VALUES ();
INSERT INTO contatto VALUES ();
INSERT INTO contatto VALUES ();
INSERT INTO fornitore VALUES();
INSERT INTO fornitore VALUES();
INSERT INTO fornitore VALUES();
INSERT INTO fornitore VALUES();
INSERT INTO fornitore VALUES();
INSERT INTO fornitore VALUES();
INSERT INTO fornitore VALUES();
INSERT INTO fornitore VALUES();
INSERT INTO fornitore VALUES();
INSERT INTO fornitore VALUES();
INSERT INTO fornitore VALUES();
INSERT INTO fornitore VALUES();
INSERT INTO fornitore VALUES();
INSERT INTO fornitore VALUES();
INSERT INTO fornitore VALUES();
INSERT INTO fornitore VALUES();
INSERT INTO fornitore VALUES();
INSERT INTO fornitore VALUES();
INSERT INTO fornitore VALUES();
INSERT INTO fornitore VALUES();
INSERT INTO fornitrice VALUES ();
INSERT INTO fornitrice VALUES ();
INSERT INTO fornitrice VALUES ();
INSERT INTO fornitrice VALUES ();
INSERT INTO fornitrice VALUES ();
INSERT INTO fornitrice VALUES ();
INSERT INTO fornitrice VALUES ();
INSERT INTO fornitrice VALUES ();
INSERT INTO indirizzo VALUES ();
INSERT INTO indirizzo VALUES ();
INSERT INTO indirizzo VALUES ();
INSERT INTO indirizzo VALUES ();
INSERT INTO indirizzo VALUES ();
INSERT INTO indirizzo VALUES ();
INSERT INTO indirizzo VALUES ();
INSERT INTO indirizzo VALUES ();
INSERT INTO indirizzo VALUES ();
INSERT INTO indirizzo VALUES ();
INSERT INTO indirizzo VALUES ();
INSERT INTO indirizzo VALUES ();
INSERT INTO indirizzo VALUES ();
INSERT INTO indirizzo VALUES ();
INSERT INTO indirizzo VALUES ();
INSERT INTO pianta VALUES ();
INSERT INTO pianta VALUES ();
INSERT INTO pianta VALUES ();
INSERT INTO pianta VALUES ();
INSERT INTO pianta VALUES ();
INSERT INTO pianta VALUES ();
INSERT INTO pianta VALUES ();
INSERT INTO pianta VALUES ();
INSERT INTO pianta VALUES ();
INSERT INTO pianta VALUES ();
INSERT INTO pianta VALUES ();
INSERT INTO pianta VALUES ();
INSERT INTO pianta VALUES ();
INSERT INTO pianta VALUES ();
INSERT INTO pianta VALUES ();
INSERT INTO pianta VALUES ();
INSERT INTO pianta VALUES ();
INSERT INTO pianta VALUES ();
INSERT INTO pianta VALUES ();
INSERT INTO pianta VALUES ();
INSERT INTO pianta VALUES ();
INSERT INTO pianta VALUES ();
INSERT INTO pianta VALUES ();
INSERT INTO pianta VALUES ();
INSERT INTO pianta VALUES ();
INSERT INTO pianta VALUES ();
INSERT INTO pianta VALUES ();
INSERT INTO pianta VALUES ();
INSERT INTO pianta VALUES ();
INSERT INTO pianta VALUES ();
INSERT INTO prezzo VALUES ();
INSERT INTO prezzo VALUES ();
INSERT INTO prezzo VALUES ();
INSERT INTO prezzo VALUES ();
INSERT INTO prezzo VALUES ();
INSERT INTO prezzo VALUES ();
INSERT INTO prezzo VALUES ();
INSERT INTO prezzo VALUES ();
INSERT INTO prezzo VALUES ();
INSERT INTO prezzo VALUES ();
INSERT INTO prezzo VALUES ();
INSERT INTO prezzo VALUES ();
INSERT INTO prezzo VALUES ();
INSERT INTO prezzo VALUES ();
INSERT INTO prezzo VALUES ();
INSERT INTO prezzo VALUES ();
INSERT INTO prezzo VALUES ();
INSERT INTO prezzo VALUES ();
INSERT INTO prezzo VALUES ();
INSERT INTO prezzo VALUES ();
INSERT INTO prezzo VALUES ();
INSERT INTO prezzo VALUES ();
INSERT INTO prezzo VALUES ();
INSERT INTO prezzo VALUES ();
INSERT INTO prezzo VALUES ();
INSERT INTO prezzo VALUES ();
INSERT INTO prezzo VALUES ();
INSERT INTO prezzo VALUES ();
INSERT INTO prezzo VALUES ();
INSERT INTO prezzo VALUES ();
INSERT INTO referente VALUES();
INSERT INTO referente VALUES();
INSERT INTO referente VALUES();
INSERT INTO referente VALUES();
INSERT INTO referente VALUES();
INSERT INTO referente VALUES();
INSERT INTO referente VALUES();
INSERT INTO referente VALUES();
INSERT INTO referente VALUES();
INSERT INTO rifornisce VALUES();
INSERT INTO rifornisce VALUES();
INSERT INTO rifornisce VALUES();
INSERT INTO rifornisce VALUES();
INSERT INTO rifornisce VALUES();
INSERT INTO rifornisce VALUES();
INSERT INTO rifornisce VALUES();
INSERT INTO rifornisce VALUES();
INSERT INTO rifornisce VALUES();
INSERT INTO rifornisce VALUES();
INSERT INTO rifornisce VALUES();
INSERT INTO rifornisce VALUES();
INSERT INTO rifornisce VALUES();
INSERT INTO rifornisce VALUES();
INSERT INTO rifornisce VALUES();
INSERT INTO rifornisce VALUES();
INSERT INTO rifornisce VALUES();
INSERT INTO rifornisce VALUES();
INSERT INTO rifornisce VALUES();
INSERT INTO rifornisce VALUES();
INSERT INTO rifornisce VALUES();
INSERT INTO rifornisce VALUES();
INSERT INTO rifornisce VALUES();
INSERT INTO rifornisce VALUES();
INSERT INTO rifornisce VALUES();
INSERT INTO rifornisce VALUES();
INSERT INTO rifornisce VALUES();
INSERT INTO rivendita VALUES();
INSERT INTO rivendita VALUES();
INSERT INTO rivendita VALUES();
INSERT INTO rivendita VALUES();
INSERT INTO rivendita VALUES();
INSERT INTO rivendita VALUES();
INSERT INTO rivendita VALUES();
INSERT INTO rivendita VALUES();
INSERT INTO rivendita VALUES();
INSERT INTO rivendita VALUES();
INSERT INTO sede VALUES('');
INSERT INTO sede VALUES('');
INSERT INTO sede VALUES('');
INSERT INTO sede VALUES('');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO specie VALUES('', '', '', '', '');
INSERT INTO tipo VALUES('esotica');
INSERT INTO tipo VALUES('interno');
INSERT INTO tipo VALUES('esterno');
INSERT INTO tipo VALUES('fiorita');